import type { TState } from './state';

export const toolsState: TState = [
    {
        index: 0,
        title: "VScode",
        desiction: "Use vscode.dev for quick edits online! ",
        href: "https://code.visualstudio.com/",
        icon: "https://code.visualstudio.com/apple-touch-icon.png",
    },
    {
        index: 1,
        title: "Chrome",
        desiction: "得益于 Google 智能工具，Chrome 现在更易用、更安全、更快速。",
        href: "https://www.google.cn/intl/zh-CN/chrome/",
        icon: "https://www.google.cn/intl/zh-CN/chrome/static/images/favicons/apple-icon-180x180.png",
    },
    {
        index: 2,
        title: "Node",
        desiction: "得益于 Google 智能工具，Chrome 现在更易用、更安全、更快速。",
        href: "https://nodejs.org/zh-cn/",
        icon: "https://nodejs.org/static/images/favicons/favicon.png",
    },
    {
        index: 3,
        title: "微信开发者工具",
        desiction: "为了帮助开发者简单和高效地开发和调试微信小程序",
        href: "https://developers.weixin.qq.com/miniprogram/dev/devtools/devtools.html",
        icon: "https://res.wx.qq.com/a/wx_fed/assets/res/NTI4MWU5.ico",
    },
    {
        index: 4,
        title: "HBuilderX",
        desiction: "当前最快的 HTML 开发工具",
        href: "https://www.dcloud.io/hbuilderx.html",
        icon: "https://download1.dcloud.net.cn/uploads/images/hbuilderx/icon/hbuilderx_icon@2x.png",
    },
    {
        index: 5,
        title: "Git",
        desiction: "Pro Gitby Scott Chacon and Ben Straub is available toread online for free",
        href: "https://git-scm.com/",
        icon: "https://git-scm.com/favicon.ico",
    },
    {
        index: 6,
        title: "火绒安全",
        desiction: "火绒安全加入麒麟软件安全生态联盟",
        href: "https://www.huorong.cn/",
        icon: "https://www.huorong.cn/assets/v5/images/logo300.png",
    },
    {
        index: 7,
        title: "uTools",
        desiction: "国产效率软件,效率工具,生产力工具",
        href: "https://www.u.tools/",
        icon: "https://www.u.tools/favicon.ico",
    },
    {
        index: 8,
        title: "Snipaste",
        desiction: "截图 + 贴图，提高您的工作效率",
        href: "https://zh.snipaste.com/",
        icon: "https://zh.snipaste.com/img/logo.svg",
    },
    {
        index: 9,
        title: "有道词典",
        desiction: "史上最强大的桌面翻译软件",
        href: "https://cidian.youdao.com/#/",
        icon: "https://cidian.youdao.com/favicon.ico",
    },
    {
        index: 10,
        title: "Apifox",
        desiction: "集接口文档工具、接口Mock工具、接口自动化测试工具、接口调试工具于一体",
        href: "https://www.apifox.cn/",
        icon: "https://cdn.apifox.cn/logo/apifox-logo-256.png",
    },
    {
        index: 11,
        title: "Python",
        desiction: "jobs.python.org Success Stories More Thanks to the flexibility of Python and the powerful ecosystem of packages",
        href: "https://www.python.org/downloads/",
        icon: "https://www.python.org/static/opengraph-icon-200x200.png",
    },
    {
        index: 12,
        title: "ToDesk",
        desiction: "ToDesk 远程控制软件是一款稳定流畅的远程控制电脑手机连接软件",
        href: "https://www.todesk.com/",
        icon: "https://www.todesk.com/favicon.ico",
    },
    {
        index: 13,
        title: "微信",
        desiction: "一款跨平台的通讯工具",
        href: "https://weixin.qq.com/",
        icon: "https://res.wx.qq.com/a/wx_fed/assets/res/OTE0YTAw.png",
    },
    {
        index: 14,
        title: "QQ",
        desiction: "8亿人在用的即时通讯软件",
        href: "https://im.qq.com/index/",
        icon: "https://qzonestyle.gtimg.cn/qzone/qzact/act/external/tiqq/logo.png",
    },
    {
        index: 15,
        title: "QQ音乐",
        desiction: "最全的高品质正版音乐曲库",
        href: "https://y.qq.com/download/index.html",
        icon: "https://y.qq.com/favicon.ico",
    },
    {
        index: 16,
        title: "网易云音乐",
        desiction: "网易云音乐是一款专注于发现与分享的音乐产品",
        href: "https://music.163.com/#/download",
        icon: "https://p3.music.126.net/tBTNafgjNnTL1KlZMt7lVA==/18885211718935735.jpg",
    },
    {
        index: 17,
        title: "WebStorm",
        desiction: "WebStorm 是我们适用于 JS 和相关技术的 IDE",
        href: "https://www.jetbrains.com.cn/webstorm/",
        icon: "https://www.jetbrains.com.cn/favicon.ico",
    },
    {
        index: 18,
        title: "IntelliJ IDEA",
        desiction: "IntelliJ IDEA 毫无疑问是软件开发者的首选 IDE",
        href: "https://www.jetbrains.com.cn/idea/",
        icon: "https://www.jetbrains.com.cn/favicon.ico",
    },
    {
        index: 19,
        title: "Navicat",
        desiction: "强大的数据库管理和设计工具",
        href: "https://www.navicat.com.cn/",
        icon: "https://www.navicat.com.cn/images/Navicat_16_Premium_win_256x256.ico",
    },
]